### ISSUE TITLE
Error "Modify on device called for Field: velocity but it has an uncleared modified_on_host"

### ISSUE THREAD

**Issue by jhux2** [Exawind/nalu-wind#908]
## Detailed description of the bug

@alanw0 @tasmith4

The heatedWaterChannelEdge test is failing with the error

```
terminating with uncaught exception of type std::logic_error: Requirement( m_modifiedOnHost == false ) FAILED
Error occurred at: stk_mesh/stk_mesh/base/FieldBase.cpp:393
 0# stk::output_stacktrace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) in /projects/ecp/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-broadwell/clang-10.0.0/trilinos-develop-o6ugq6okuqo7743tspxvssfp6y4si2qu/lib/libstk_util_util.so.13
 1# stk::mesh::FieldBase::modify_on_device() const in /projects/ecp/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-broadwell/clang-10.0.0/trilinos-develop-o6ugq6okuqo7743tspxvssfp6y4si2qu/lib/libstk_mesh_base.so.13
 2# 0x00000000008C5033 in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
 3# 0x00000000008EEB76 in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
 4# 0x00000000008C4D95 in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
 5# 0x00000000008A1313 in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
 6# 0x000000000084383F in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
 7# 0x0000000000AA96AE in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
 8# 0x000000000079998B in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
 9# 0x000000000079ACE5 in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
10# 0x0000000000792106 in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
11# 0x000000000074B2C6 in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX
12# __libc_start_main in /lib64/libc.so.6
13# 0x000000000067589B in /projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/naluX

Error: Modify on device called for Field: velocity but it has an uncleared modified_on_host
```

The failure started on October 28th (https://my.cdash.org/test/44349680) with Trilinos commit 0e7c14a41c9.  The offending commits are probably in `git log bc4e9f6f09c^..0e7c14a41c9`.

I'm also seeing the same failure in a CPU run on Summit using the unrefined NREL5MW mesh.

**Comment by alanw0** [comment]
This should be fixed by #907

**Comment by jhux2** [comment]
@alanw0 I still see this error when running nalu-wind with the unrefined NREL5MW mesh.  I can't get a stacktrace from the corefiles on Summit, not sure why.

**Comment by jhux2** [comment]
@alanw0 I can confirm that PR #907 fixes the heatedWaterChannelEdge error on Summit.

**Comment by jhux2** [comment]
Based on the PR, I'm assuming there's still one or more missing `sync_to_device` statements.

**Comment by psakievich** [comment]
Unfortunately I think there are going to be many of these to fix. I just ran another case for some dev work and got this uncleared modified_on_host error for the iddes_rans_indicator. Ugh I will have to deal with this tomorrow.

**Comment by alanw0** [comment]
Yes, possibly so. The issue is, stk is now pickier about making sure you can't mark a field as modified-on-device when you have already marked it as modified-on-host, without an intervening sync. When we made this change in the sierra repository, it didn't cause any problems in the sierra applications. Unfortunately, it seems as though nalu-wind has been living dangerously in this regard, and the sync_to_host/device calls are not placed close enough to the modify_on_device/host calls, and some seem to be missing. I'm surprised it's not a correctness issue. (Maybe it is...)

**Comment by alanw0** [comment]
I'm debugging more of the tests now, I expect to have another PR up soon.
The general pattern that should be followed for gpu kernels that modify a field, is this:
execute() {
  field.sync_to_device();
  run_kernel(); //i.e., kokkos::parallel_for
  field.modify_on_device();
}
We've worked very hard to make sure that sync_to_host/sync_to_device is extremely fast when no sync is necessary (It won't even fence if no sync is necessary, in the latest stk update. I'm not sure if that update is in trilinos yet but it's coming.). So if we're running multiple kernels in succession, and the field is already up-to-date on device, it's ok to call sync_to_device again. It won't do un-necessary work. In nalu-wind, we have a lot of algorithm/kernels that don't necessarily know which other kernels are being run when, and I think we've tried to be too clever about locating the sync_to_device calls at higher scopes to avoid un-necessary syncs. We need to follow the above pattern more consistently.

**Comment by jhux2** [comment]
@alanw0 Thanks for looking at these.  stk looks to be creating a stacktrace (see the issue description above), but there aren't any line numbers.  Would this trace have line numbers in a debug build?

**Comment by alanw0** [comment]
@jhux2 stk's stacktrace just calls a boost stacktrace, I'm not sure when it can be counted on. I'm guessing a debug build would have a better chance... What we really want there is to know where in nalu-wind made the call to modify_on_device().

**Comment by jhux2** [comment]
Btw, I'm running on CPU only.  Shouldn't modify_on_device() be a no-op?  Also, on Summit running with the NREL5MW mesh, I see

```
Error: Modify on device called for Field: minimum_distance_to_wall but it has an uncleared modified_on_host
```

Is there more information I could provide to help diagnose?

**Comment by sayerhs** [comment]
@jhux2 How far along has nalu-wind got to in the log file before you see this exception? It might be possible to guess at the likely culprit algorithm that is calling this modify_on_device.

**Comment by alanw0** [comment]
Regarding @jhux2 's question "shouldn't modify_on_device be a no-op on CPU". We've discussed this a lot on the stk team. The winning argument so far is that if the calling code is calling modify_on_device and then modify_on_host without an intervening sync, we don't want that to happily work on CPU if it will either fail or give wrong answers when running on GPU. I.e., we don't want to allow wrong calling-app logic on CPU and then have to debug it on GPU. On CPU those calls are all nearly no-ops, but they do set bools and insist that the bools are consistent/logical.

**Comment by sayerhs** [comment]
@alanw0  the field pointed to by @jhux2  should only be modified in this block

https://github.com/Exawind/nalu-wind/blob/99cdca539b58591d50f5d792de0bdf881c7a253a/src/WallDistEquationSystem.C#L487-L503

**Comment by alanw0** [comment]
Thanks @sayerhs I'll look at that.

**Comment by sayerhs** [comment]
Sorry for NREL 5MW case, this block might be activated also: 

https://github.com/Exawind/nalu-wind/blob/99cdca539b58591d50f5d792de0bdf881c7a253a/src/ShearStressTransportEquationSystem.C#L433-L445

If the log files indicate that the error is happening after it enters a timestep, this is the likely block.

**Comment by alanw0** [comment]
@sayerhs @jhux2 Line 487 in the snippet above, may be where the throw is coming from. Line 472 in that file is a device loop, and there should be a sync_to_device call prior to line 472. A sync_to_device call prior to 472 would clear a modify-on-host flag if it had been set before then.

**Comment by jhux2** [comment]
@sayerhs @alanw0 Sorry, was in a meeting.  I put in some extra print's, and the throw happens sometime after the call
`(*ii)->advance_time_step()` in TimeIntegrator.C.

**Comment by jhux2** [comment]
@sayerhs wrote:
> Sorry for NREL 5MW case, this block might be activated also:
> 
> https://github.com/Exawind/nalu-wind/blob/99cdca539b58591d50f5d792de0bdf881c7a253a/src/ShearStressTransportEquationSystem.C#L433-L445

Should this also have a `ndtw.sync_to_device()` call just before line 433?
Should there be a `ndtw.sync_to_host()` just after line 440?

**Comment by alanw0** [comment]
@jhux2 yes there should be ndtw.sync_to_device() before 433. I don't think there should be sync_to_host() after 440, sync_to_host should happen in the code that next needs/uses that field on host. The stk communication calls such as stk::mesh::parallel_max do sync_to_host on the field, for example.
I'm getting close on a nalu-wind PR which will tackle the things noted in this thread, plus a couple others I've been debugging this morning from the dashboard.

**Comment by jhux2** [comment]
I made the suggested changes and the NREL5MW runs to completion.  Thanks!
```diff --git a/src/WallDistEquationSystem.C b/src/WallDistEquationSystem.C
index c2b4ede4..ac31c5ca 100644
--- a/src/WallDistEquationSystem.C
+++ b/src/WallDistEquationSystem.C
@@ -469,6 +469,7 @@ WallDistEquationSystem::compute_wall_distance()
     wallDistance_->mesh_meta_data_ordinal());
   const stk::mesh::Selector sel = stk::mesh::selectField(*wallDistPhi_);

+  wdist.sync_to_device();
   nalu_ngp::run_entity_algorithm(
     "compute_wall_dist",
     ngpMesh, stk::topology::NODE_RANK, sel, KOKKOS_LAMBDA(const MeshIndex& mi) {
```

```
diff --git a/src/ShearStressTransportEquationSystem.C b/src/ShearStressTransportEquationSystem.C
index 4a70bc3c..d60a998e 100644
--- a/src/ShearStressTransportEquationSystem.C
+++ b/src/ShearStressTransportEquationSystem.C
@@ -430,6 +430,7 @@ ShearStressTransportEquationSystem::clip_min_distance_to_wall()
     (meta.locally_owned_part() | meta.globally_shared_part()) &
     stk::mesh::selectUnion(wallBcPart_);

+  ndtw.sync_to_device();
   nalu_ngp::run_entity_algorithm(
     "SST::clip_ndtw", ngpMesh, stk::topology::NODE_RANK, sel,
     KOKKOS_LAMBDA(const MeshIndex& mi) {
```

**Comment by alanw0** [comment]
@jhux2 Great, glad to hear that. I'll go ahead and merge it, and continue my debugging on a couple other things.

**Comment by jhux2** [comment]
Fixed by #910.  Thank you, @alanw0 and @sayerhs!

**Comment by psakievich** [comment]
@alanw0 is there a specific reason why we separate the `sync` and `modify` calls?  It seems to me like we could put them in the same place since `modify_on_device` is just setting a state.  Just a thought, but could we even go so far as to make them a single call in this case to reduce the chance for bugs going forward?

**Comment by alanw0** [comment]
@psakievich No, they're logically separate. sync_to_device says 'I want the most updated data to be on device'. So you would do that for any fields you're about to reference, either read-only or read-write. modify_on_device says 'I changed the data on device'. So you would only do that for fields that were written to.

**Comment by psakievich** [comment]
@alanw0 sure that makes sense. I guess I'm thinking you could have `field.sync_to_device()` and `field.sync_and_modify_device()`.   so the kernel execution would look like this
```c++
fieldToChange.sync_and_modify_device();
fieldToReference.sync_to_device();
kokkos::parallel_for(...);
```
This would just eliminate the need to call modify after the execution.

**Comment by tasmith4** [comment]
@psakievich The issue there is that "sync_and_modify_device" is only one of 3 potential use cases:
* Read-only:  sync_device
* Read-write:  sync_device, modify_device
* Overwrite:  clear_sync_state, modify_device

**Comment by sayerhs** [comment]
Apologies to everyone for continuing on a closed thread. But I had a question for @alanw0 

So, I understand that putting `sync_to_device` is a lightweight op and will clear the flags. However, for this `ndtw` field, I can't explain to myself where the host flags were set. The only place we call `modify_on_host` for this field is in Line 502 in `WallDistanceEquationSystem.C`. @alanw0  do you see where the host flags were set for this particular field? This is just for my understanding.

**Comment by alanw0** [comment]
@sayerhs It's probably getting marked modified-on-host by a stk communication routine. If not, we could track it down with a little more effort.

**Comment by sayerhs** [comment]
@alanw0 OK. I was wondering about that. I remember that we had set calls like `copy_owned_to_shared` etc to not sync to device previously in Nalu-Wind to stack multiple shared/ghosting exchanges. However, I was expecting L503 to have cleared any flags set at STK calls. So this was a little puzzling to me. I think it would be good to be able to explain this behavior to make sure we haven't overlooked a subtle bug in nalu-wind.

https://github.com/Exawind/nalu-wind/blob/99cdca539b58591d50f5d792de0bdf881c7a253a/src/WallDistEquationSystem.C#L491-L503

**Comment by alanw0** [comment]
@sayerhs Yes the sync call at line 503 should clear the flags. I think the error was showing up in the modify_on_device call at line 487. My change yesterday fixed that by inserting a sync_to_device at line 472.
